MoveRelearner_Text_WouldLearnNewMoves:
	.string "{JPN}ぼく わざマニア\n"
	.string "どの しゅるいの わざに するんだい?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Level Up Moves$"

MoveRelearner_Text_EggMoves:
	.string "Egg Moves$"

MoveRelearner_Text_TMMoves:
	.string "TM Moves$"

MoveRelearner_Text_TutormoveMoves:
	.string "Tutor Moves$"

MoveRelearner_Text_SeeYa:
	.string "やめる$"

MoveRelearner_Text_AnythingElse:
	.string "{JPN}どの しゅるいの わざに するんだい？$"

MoveRelearner_Text_ChoosePkmn:
	.string "{JPN}どの ポケモンに するんだい?$"

MoveRelearner_Text_HaveNoPkmn:
	.string "{JPN}ポケモンが いないよ$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "{JPN}えっ?\nタマゴに おしえられる わざは ないよ$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "{JPN}ごめんね……\pぼくが その ポケモンに\nおしえられる わざは ないみたいだよ$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "{ENG}Level up move{JPN}$"

MoveRelearner_Text_EggMoveLWR::
	.string "{ENG}Egg move{JPN}$"

MoveRelearner_Text_TMMoveLWR::
	.string "{ENG}TM move{JPN}$"

MoveRelearner_Text_TutorMoveLWR::
	.string "{ENG}Tutor move{JPN}$"

MoveRelearner_Text_MoveLWR::
	.string "{ENG}move{JPN}$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "{JPN}どの {STR_VAR_3} にするんだい?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "{JPN}また おいで！$"
